### PR TITLE
workaround SR-11125: @_implementationOnly import CNIOBoringSSL

### LINKED ISSUE #116: build error on Ubuntu 18, Swift 5.1 : "reference to 'SHA256_CTX' is ambiguous"
I'm trying to build swift-nio-ssl on an Ubuntu 18 machine, using Swift 5.1, as part of a server based on Vapor 4 alpha (yes I know). Everything builds fine except for the following error :

`<unknown>:0: error: reference to 'SHA256_CTX' is ambiguous
/srv/datadisk01/www/VideoSaverServer/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL/base.h:411:32: note: candidate found by name lookup is 'SHA256_CTX'
typedef struct sha256_state_st SHA256_CTX;
                               ^
//usr/include/openssl/sha.h:56:3: note: candidate found by name lookup is 'SHA256_CTX'
} SHA256_CTX;
  ^
Failed to reconstruct type for $sSo10SHA256_CTXaD
Original type:
(type_alias_type decl=CAPNSOpenSSL.(file).SHA256_CTX)`

Is that error expected somehow ? I have libssl 1.1 installed on this server, on which the vapor package depends.

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

If we don't import CNIOBoringSSL @_implementationOnly, then some details
of libssl's C structs might leak into NIOSSL's ABI which might lead to
clashes further down the line.

Modification:
- make all CNIOBoringSSL(Shims) imports @_implementationOnly
- remove all concrete libssl types from instance variables

Result:
- fixes #116
- works around SR-11125
- thanks @jrose-apple for suggesting this

### CODE REVIEW

File: Sources/NIOSSL/SSLCertificate.swift [hunk 1]
```diff
@@ -39,7 +48,7 @@ public class NIOSSLCertificate {
     }
 
     private init(withReference ref: UnsafeMutablePointer<X509>) {
-        self.ref = ref
+        self._ref = .init(ref)
```
Comment (Lukasa) [inline Sources/NIOSSL/SSLCertificate.swift]: While I appreciate the desire to make this concise, when it comes to working with the pointer types I really prefer being able to see what the actual type is at the point of initialisation, rather than finding the declaration. Can we use the longer form initializer here?

File: Sources/NIOSSL/SSLCertificate.swift [hunk 2]
```diff
@@ -102,7 +111,7 @@ public class NIOSSLCertificate {
     ///
     /// In general, however, this function should be avoided in favour of one of the convenience
     /// initializers, which ensure that the lifetime of the `X509` object is better-managed.
-    static public func fromUnsafePointer(takingOwnership pointer: UnsafeMutablePointer<X509>) -> NIOSSLCertificate {
+    static func fromUnsafePointer(takingOwnership pointer: UnsafeMutablePointer<X509>) -> NIOSSLCertificate {
```
Comment (Lukasa) [inline Sources/NIOSSL/SSLCertificate.swift]: This is technically a breaking API change. Do we want to ship a 3.0 here? Or do we think this can be made an exception?

File: Sources/NIOSSL/SSLPrivateKey.swift [hunk 3]
```diff
@@ -112,10 +116,14 @@ func globalBoringSSLPassphraseCallback(buf: UnsafeMutablePointer<CChar>?,
...
-    internal let ref: UnsafeMutablePointer<EVP_PKEY>
+    internal let _ref: UnsafeMutableRawPointer /*<EVP_PKEY>*/
+
+    internal var ref: UnsafeMutablePointer<EVP_PKEY> {
+        return self._ref.assumingMemoryBound(to: EVP_PKEY.self)
+    }
 
     private init(withReference ref: UnsafeMutablePointer<EVP_PKEY>) {
-        self.ref = ref
+        self._ref = .init(ref)
```
Comment (Lukasa) [inline Sources/NIOSSL/SSLPrivateKey.swift]: Same comment about the initialisation here.

File: Sources/NIOSSL/SSLPublicKey.swift [hunk 4]
```diff
@@ -21,10 +25,14 @@ import CNIOBoringSSL
...
-    private let ref: UnsafeMutablePointer<EVP_PKEY>
+    private let _ref: UnsafeMutableRawPointer /*<EVP_PKEY>*/
+
+    private var ref: UnsafeMutablePointer<EVP_PKEY> {
+        return self._ref.assumingMemoryBound(to: EVP_PKEY.self)
+    }
 
     fileprivate init(withOwnedReference ref: UnsafeMutablePointer<EVP_PKEY>) {
-        self.ref = ref
+        self._ref = .init(ref)
```
Comment (Lukasa) [inline Sources/NIOSSL/SSLPublicKey.swift]: Same comment about the initialisation here.

File: Sources/NIOSSL/SSLCertificate.swift (hunk 2 above)
Comment (weissi) [reply Sources/NIOSSL/SSLCertificate.swift]: Yup, my vote goes for exception. There was never a legal way to obtain an `UnsafeMutablePointer<X509>` (with the _right_ `X509`...).

Comment (Lukasa) [reply Sources/NIOSSL/SSLCertificate.swift]: I think I agree.
